// Generated by gencpp from file opencv_cam/clu.msg
// DO NOT EDIT!


#ifndef OPENCV_CAM_MESSAGE_CLU_H
#define OPENCV_CAM_MESSAGE_CLU_H

#include <ros/service_traits.h>


#include <opencv_cam/cluRequest.h>
#include <opencv_cam/cluResponse.h>


namespace opencv_cam
{

struct clu
{

typedef cluRequest Request;
typedef cluResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct clu
} // namespace opencv_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opencv_cam::clu > {
  static const char* value()
  {
    return "51b41483a7964797e1bc083c1c92baf4";
  }

  static const char* value(const ::opencv_cam::clu&) { return value(); }
};

template<>
struct DataType< ::opencv_cam::clu > {
  static const char* value()
  {
    return "opencv_cam/clu";
  }

  static const char* value(const ::opencv_cam::clu&) { return value(); }
};


// service_traits::MD5Sum< ::opencv_cam::cluRequest> should match
// service_traits::MD5Sum< ::opencv_cam::clu >
template<>
struct MD5Sum< ::opencv_cam::cluRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_cam::clu >::value();
  }
  static const char* value(const ::opencv_cam::cluRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_cam::cluRequest> should match
// service_traits::DataType< ::opencv_cam::clu >
template<>
struct DataType< ::opencv_cam::cluRequest>
{
  static const char* value()
  {
    return DataType< ::opencv_cam::clu >::value();
  }
  static const char* value(const ::opencv_cam::cluRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opencv_cam::cluResponse> should match
// service_traits::MD5Sum< ::opencv_cam::clu >
template<>
struct MD5Sum< ::opencv_cam::cluResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_cam::clu >::value();
  }
  static const char* value(const ::opencv_cam::cluResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_cam::cluResponse> should match
// service_traits::DataType< ::opencv_cam::clu >
template<>
struct DataType< ::opencv_cam::cluResponse>
{
  static const char* value()
  {
    return DataType< ::opencv_cam::clu >::value();
  }
  static const char* value(const ::opencv_cam::cluResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENCV_CAM_MESSAGE_CLU_H
