// Generated by gencpp from file opencv_cam/cluResponse.msg
// DO NOT EDIT!


#ifndef OPENCV_CAM_MESSAGE_CLURESPONSE_H
#define OPENCV_CAM_MESSAGE_CLURESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opencv_cam
{
template <class ContainerAllocator>
struct cluResponse_
{
  typedef cluResponse_<ContainerAllocator> Type;

  cluResponse_()
    : result(0)  {
    }
  cluResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::opencv_cam::cluResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_cam::cluResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cluResponse_

typedef ::opencv_cam::cluResponse_<std::allocator<void> > cluResponse;

typedef boost::shared_ptr< ::opencv_cam::cluResponse > cluResponsePtr;
typedef boost::shared_ptr< ::opencv_cam::cluResponse const> cluResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_cam::cluResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_cam::cluResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opencv_cam::cluResponse_<ContainerAllocator1> & lhs, const ::opencv_cam::cluResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opencv_cam::cluResponse_<ContainerAllocator1> & lhs, const ::opencv_cam::cluResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opencv_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::opencv_cam::cluResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_cam::cluResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_cam::cluResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_cam::cluResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_cam::cluResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_cam::cluResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_cam::cluResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::opencv_cam::cluResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_cam::cluResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_cam/cluResponse";
  }

  static const char* value(const ::opencv_cam::cluResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_cam::cluResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
;
  }

  static const char* value(const ::opencv_cam::cluResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_cam::cluResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cluResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_cam::cluResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_cam::cluResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_CAM_MESSAGE_CLURESPONSE_H
